# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='商品编号')),
                ('name', models.CharField(db_index=True, default='', max_length=100, verbose_name='商品名称')),
                ('click_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('market_price', models.FloatField(default=0.0, verbose_name='市场价')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_publish', models.BooleanField(default=False, verbose_name='上架')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
